spring.application.name=ApiGateway
server.port=9000
# 1. Pointer vers le serveur Eureka de Badr
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 2. Activer la découverte des microservices
spring.cloud.gateway.discovery.locator.enabled=true

# 3. Forcer l'utilisation des minuscules dans l'URL (très important !)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route pour l'API standard (HTTP)
spring.cloud.gateway.routes[0].id=communication-api
spring.cloud.gateway.routes[0].uri=lb://communication-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/communication-service/api/**

# Route spécifique pour le WebSocket (STOMP)
spring.cloud.gateway.routes[1].id=communication-websocket
spring.cloud.gateway.routes[1].uri=lb://communication-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/communication-service/ws-chat/**